import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ColumnDef, flexRender, getCoreRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table'
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api, Dataset, Flow, ModelMetrics } from './api'
import './styles.css'

function Async({ loading, error, children }: { loading: boolean; error?: string; children: React.ReactNode }) { return loading ? <div className="state">Loading analysis data…</div> : error ? <div className="state error">{error}</div> : <>{children}</> }
function App() { return <BrowserRouter><div className="shell"><aside><Link className="brand" to="/">Encrypt<span>Sight</span></Link><p>Network intelligence</p><nav><NavLink to="/">Dashboard</NavLink><NavLink to="/upload">New analysis</NavLink><NavLink to="/models">Model info</NavLink></nav><div className="lane-note">Two independent model lanes:<br/>UNSW-NB15 · CICIDS2017</div></aside><main><Routes><Route path="/" element={<Dashboard/>}/><Route path="/upload" element={<Upload/>}/><Route path="/datasets/:id" element={<DatasetDetail/>}/><Route path="/flows/:id" element={<FlowDetail/>}/><Route path="/models" element={<ModelInfo/>}/></Routes></main></div></BrowserRouter> }

function Dashboard() { const [datasets, setDatasets] = useState<Dataset[]>([]), [models, setModels] = useState<any>({}), [summary, setSummary] = useState<any>(), [error, setError] = useState(''); useEffect(() => { Promise.all([api.datasets(), api.activeModel('unsw_nb15'), api.activeModel('cicids2017').catch(() => null)]).then(([d, u, c]) => { setDatasets(d); setModels({u,c}); if(d[0]) api.summary(d[0].id).then(setSummary).catch(e => setError(e.message)) }).catch(e => setError(e.message)) }, []); const chart = Object.entries(summary?.predictions_count ?? {}).map(([name, value]) => ({name,value})); return <Async loading={!error && !datasets && false} error={error}><header><div><h1>Threat analysis dashboard</h1><p>Recent flow classification runs and model health.</p></div><Link className="button" to="/upload">Upload CSV</Link></header><section className="cards"><Card label="Datasets analyzed" value={datasets.length}/><Card label="Flows scored" value={datasets.reduce((n,d) => n+d.row_count, 0).toLocaleString()}/><Card label="UNSW active" value={models.u?.version_label ?? 'Loading…'}/><Card label="CICIDS active" value={models.c?.version_label ?? 'Not trained'}/></section><section className="grid"><article><h2>Past analyses</h2><table><thead><tr><th>File</th><th>Lane</th><th>Flows</th><th>Uploaded</th></tr></thead><tbody>{datasets.map(d => <tr key={d.id}><td><Link to={`/datasets/${d.id}`}>{d.source_file}</Link></td><td>{d.name}</td><td>{d.row_count.toLocaleString()}</td><td>{new Date(d.uploaded_at).toLocaleString()}</td></tr>)}{!datasets.length && <tr><td colSpan={4}>No datasets have been analyzed yet.</td></tr>}</tbody></table></article><article><h2>Latest class distribution</h2>{chart.length ? <ResponsiveContainer width="100%" height={260}><PieChart><Pie data={chart} dataKey="value" nameKey="name" outerRadius={90}>{chart.map((_,i) => <Cell key={i} fill={['#38bdf8','#f97316','#a78bfa','#34d399','#f43f5e'][i%5]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer> : <p className="muted">Upload a dataset to see distribution.</p>}</article></section></Async> }
function Card({label,value}:{label:string;value:string|number}) { return <article className="card"><span>{label}</span><strong>{value}</strong></article> }

function Upload() { const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''); const navigate=useNavigate(); async function submit(f=file) { if(!f)return; setBusy(true);setError(''); try { const start=await api.upload(f); setMessage(`Upload accepted. Scoring up to ${start.max_analysis_rows.toLocaleString()} flows in the background…`); let job:any; do { await new Promise(resolve=>setTimeout(resolve,1000)); job=await api.job(start.job_id) } while(job.status==='queued'||job.status==='processing'); if(job.status==='failed') throw new Error(job.detail); const r=job.result; setMessage(`${r.truncated ? `First ${r.row_count.toLocaleString()} of ${r.source_row_count.toLocaleString()} flows analyzed. ` : ''}Detected: ${r.schema_type === 'unsw' ? 'UNSW-NB15' : 'CICIDS2017'} schema`); navigate(`/datasets/${r.dataset_id}`) } catch(e:any){setError(e.message)} finally{setBusy(false)} } return <><header><div><h1>New analysis</h1><p>Upload a CSV from one supported network-flow schema.</p></div></header><article className="upload"><input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files?.[0]??null)}/><p>{file?.name ?? 'Choose a UNSW-NB15 or CICIDS2017 CSV file.'}</p><button className="button" disabled={!file||busy} onClick={()=>submit()}>{busy?'Scoring in background…':'Analyze CSV'}</button><p className="muted">Interactive uploads analyze up to 2,000 flows so the dashboard stays responsive. Use the bundled datasets to try either lane.</p>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}</article></> }

function DatasetDetail() { const {id=''}=useParams(); const [dataset,setDataset]=useState<Dataset>(),[flows,setFlows]=useState<Flow[]>([]),[matrix,setMatrix]=useState<any>(),[page,setPage]=useState(1),[total,setTotal]=useState(0),[filter,setFilter]=useState(''),[error,setError]=useState(''); useEffect(()=>{api.dataset(id).then(d=>{setDataset(d);return Promise.all([api.flows(id,page,filter?{predicted_label:filter}:{}),api.matrix(d.name)])}).then(([f,m])=>{setFlows(f.flows);setTotal(f.total_count);setMatrix(m)}).catch(e=>setError(e.message))},[id,page,filter]); const columns=useMemo<ColumnDef<Flow>[]>(()=>[{header:'Class',cell:x=><span className={x.row.original.predicted_label?'attack':'benign'}>{x.row.original.predicted_attack_cat ?? (x.row.original.predicted_label?'Attack':'Benign')}</span>},{header:'Confidence',accessorKey:'confidence',cell:x=>`${(Number(x.getValue())*100).toFixed(1)}%`},{header:'Ground truth',accessorKey:'true_label',cell:x=>x.getValue()==null?'—':Number(x.getValue())?'Attack':'Benign'},{header:'Inspect',cell:x=><Link to={`/flows/${x.row.original.id}`}>View →</Link>}],[]); const table=useReactTable({data:flows,columns,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel()}); return <Async loading={!dataset&&!error} error={error}>{dataset&&<><header><div><h1>{dataset.source_file}</h1><p>{dataset.name} · {dataset.row_count.toLocaleString()} flows</p></div></header><section className="grid"><article><h2>Confusion matrix</h2>{matrix&&<Matrix {...matrix}/>}</article><article><h2>Flow table</h2><label>Predicted class <select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="">All</option><option value="0">Benign</option><option value="1">Attack</option></select></label><table><thead>{table.getHeaderGroups().map(h=><tr key={h.id}>{h.headers.map(c=><th key={c.id} onClick={c.column.getToggleSortingHandler()}>{flexRender(c.column.columnDef.header,c.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id}>{r.getVisibleCells().map(c=><td key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table><div className="pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} · {total.toLocaleString()} flows</span><button disabled={page*50>=total} onClick={()=>setPage(page+1)}>Next</button></div></article></section></>}</Async> }
function Matrix({classes,matrix}:{classes:string[];matrix:number[][]}) { const max=Math.max(...matrix.flat(),1); return <div className="matrix">{matrix.map((row,i)=><div className="matrix-row" key={classes[i]}><b>{classes[i]}</b>{row.map((v,j)=><span key={j} title={`${classes[i]} → ${classes[j]}: ${v}`} style={{backgroundColor:`rgba(14,116,144,${.15+.85*v/max})`,color:v/max>.45?'white':'#0f172a'}}>{v}</span>)}</div>)}</div> }

function FlowDetail(){ const {id=''}=useParams(); const [flow,setFlow]=useState<Flow>(),[items,setItems]=useState<any[]>([]),[error,setError]=useState(''); useEffect(()=>{Promise.all([api.flow(id),api.explanation(id)]).then(([f,e])=>{setFlow(f);setItems(e)}).catch(e=>setError(e.message))},[id]); const sorted=[...items].sort((a,b)=>Math.abs(b.shap_value)-Math.abs(a.shap_value)).slice(0,15); return <Async loading={(!flow||!items.length)&&!error} error={error}><header><div><h1>Flow explanation</h1><p>On-demand SHAP values are cached after the first calculation.</p></div></header>{flow&&<section className="cards"><Card label="Prediction" value={flow.predicted_attack_cat ?? (flow.predicted_label?'Attack':'Benign')}/><Card label="Confidence" value={`${(flow.confidence*100).toFixed(1)}%`}/></section>}<section className="grid"><article><h2>SHAP feature impact</h2><ResponsiveContainer width="100%" height={440}><BarChart layout="vertical" data={sorted}><XAxis type="number"/><YAxis dataKey="feature_name" type="category" width={140}/><Tooltip/><Bar dataKey="shap_value">{sorted.map((x,i)=><Cell key={i} fill={x.shap_value>=0?'#ef4444':'#2563eb'}/>)}</Bar></BarChart></ResponsiveContainer></article><article><h2>Raw feature values</h2><table><tbody>{Object.entries(flow?.raw_features_json ?? {}).map(([name,value])=><tr key={name}><th>{name}</th><td>{String(value)}</td></tr>)}</tbody></table></article></section></Async> }

function ModelInfo(){ const [lane,setLane]=useState('unsw_nb15'),[model,setModel]=useState<{version_label:string;metrics:ModelMetrics}>(),[error,setError]=useState(''); useEffect(()=>{setModel(undefined);setError('');api.activeModel(lane).then(setModel).catch(e=>setError(e.message))},[lane]); const importance=(model?.metrics.feature_importance??[]).slice(0,15).map(([name,value])=>({name,value})); const report=Object.entries(model?.metrics.classification_report??{}).filter(([n])=>!['accuracy','macro avg','weighted avg'].includes(n)); return <Async loading={!model&&!error} error={error}><header><div><h1>Model information</h1><p>Schema lanes are separate and cannot be used interchangeably.</p></div><select value={lane} onChange={e=>setLane(e.target.value)}><option value="unsw_nb15">UNSW-NB15</option><option value="cicids2017">CICIDS2017</option></select></header>{model&&<><section className="cards"><Card label="Version" value={model.version_label}/><Card label="Accuracy" value={`${(model.metrics.accuracy*100).toFixed(1)}%`}/></section><section className="grid"><article><h2>Feature importance</h2><ResponsiveContainer width="100%" height={430}><BarChart layout="vertical" data={importance}><XAxis type="number"/><YAxis type="category" dataKey="name" width={135}/><Tooltip/><Bar dataKey="value" fill="#f97316"/></BarChart></ResponsiveContainer></article><article><h2>Per-class performance</h2><table><thead><tr><th>Class</th><th>Precision</th><th>Recall</th><th>F1</th><th>Support</th></tr></thead><tbody>{report.map(([name,r])=><tr key={name}><td>{name}</td><td>{r.precision?.toFixed(2)}</td><td>{r.recall?.toFixed(2)}</td><td>{r['f1-score']?.toFixed(2)}</td><td>{r.support}</td></tr>)}</tbody></table></article></section><article className="limitations"><h2>Known limitations</h2><p>UNSW-NB15 minority classes—Analysis, Backdoor, Shellcode, and Worms—are more often confused with each other and with larger categories. DoS, Exploits, Fuzzers, and Normal also show meaningful overlap. Review individual flows and confidence; accuracy is not uniform across classes.</p></article></>}</Async> }
createRoot(document.getElementById('root')!).render(<App />)
